#!/bin/bash

# Script name for error messages
PROGNAME=$( basename $0 )

# Either "stream" for production, or "recording" for testing
#OUTPUT="recording"
OUTPUT="stream"

# Location to calculate sunrise/sunset times
LAT="44.45474N"
LON="88.08082W"

# Opening/starting soon scene
SCENESTART="Opening 0"

# Scene when the stream is "live"
SCENELIVE="Chick View"

if [[ ! -x /usr/bin/obs ]]
then
	echo "${PROGNAME}: Unable to run OBS"
	exit 1
fi

if [[ ! -x ${HOME}/bin/ydotool ]]
then
	echo "${PROGNAME}: Unable to run ydotool"
	exit 1
fi

if [[ ! -x ${HOME}/bin/obs-cli ]]
then
	echo "${PROGNAME}: Unable to run obs-cli"
	exit 1
fi

# Write today's sunset time to be used in the on screen display
SUNSET=$( date --date=$(sunwait ${LAT} ${LON} list sunset) +%l:%M%P )
echo "sunsettime='${SUNSET}';" >~/OBS/clock/sunset.js

# Nice message for the log
SUNRISE=$( sunwait ${LAT} ${LON} list rise offset 45 )
echo "${PROGNAME}: Waiting for sunrise at ${SUNRISE}"

# Wait for sunrise
sunwait ${LAT} ${LON} wait rise offset 45

# Start OBS; give it a few seconds to load
/usr/bin/obs &
sleep 5

# Switch to the intro scene
obs-cli scene current ${SCENESTART}

# Start the network stream
obs-cli ${OUTPUT} start

# Time for intro to play
sleep 30

# Switch to the main live stream scene
obs-cli scene current ${SCENELIVE}
