#!/bin/bash

# Script name for error messages
PROGNAME=$( basename $0 )

# Either "stream" for production, or "recording" for testing
#OUTPUT="recording"
OUTPUT="stream"

# Location to calculate sunrise/sunset times
LAT="44.45474N"
LON="88.08082W"

# Closing/ending scene
SCENEEND="Closing 0"

if ! pgrep -U ${USER} obs >/dev/null
then
	echo "${PROGNAME}: OBS not running"
	exit 0
fi

if [[ ! -x ${HOME}/bin/ydotool ]]
then
	echo "${PROGNAME}: Unable to run ydotool"
	exit 1
fi

if [[ ! -x ${HOME}/bin/obs-cli ]]
then
	echo "${PROGNAME}: Unable to run obs-cli"
	exit 1
fi

# Nice message for the log
SUNSET=$( sunwait ${LAT} ${LON} list set )
echo "${PROGNAME}: Waiting for sunset at ${SUNSET}"

# Wait for sunset
sunwait ${LAT} ${LON} wait set

# Activate the end of stream scene 
obs-cli scene current ${SCENEEND}

# Time for ending to play
sleep 30

# End the recording/network stream
obs-cli ${OUTPUT} stop
sleep 5

${HOME}/bin/ydotool key 29:1 16:1 29:0 16:0

# Set the blank delay time to enable the screensaver
gsettings set org.gnome.desktop.session idle-delay 300
