#!/bin/bash

# Script name for error messages
PROGNAME=$( basename $0 )

# Read settings from available config file
if [[ -z "$XDG_CONFIG_HOME" ]]
then
	CFG="$HOME/.config"
else
	CFG="${XDG_CONFIG_HOME}"
fi

CFG="${CFG}/obs-stream.conf"

if [[ -r "${CFG}" ]]
then
	source ${CFG}
fi

# Optional paramater for sunwait
if [[ -n "${SUNSET_OFFSET}" ]] && (( ${SUNSET_OFFSET} != 0 ))
then
	SUNSET_OFFSET="offset ${SUNSET_OFFSET}"
else
	SUNSET_OFFSET=""
fi

# Either "stream" for production, or "recording" for testing
#OUTPUT="recording"
OUTPUT="stream"

# Location to calculate sunrise/sunset times
LOCATION="${LATITUDE} ${LONGITUDE}"

# Closing/ending scene
SCENEEND="Closing 0"

if ! pgrep -U ${USER} obs >/dev/null
then
	echo "${PROGNAME}: OBS not running"
	exit 0
fi

if [[ ! -x ${HOME}/bin/ydotool ]]
then
	echo "${PROGNAME}: Unable to run ydotool"
	exit 1
fi

if [[ ! -x ${HOME}/bin/obs-cli ]]
then
	echo "${PROGNAME}: Unable to run obs-cli"
	exit 1
fi

# Nice message for the log
SUNSET=$( sunwait ${LOCATION} list sunset ${SUNSET_OFFSET} )
echo "${PROGNAME}: Waiting for sunset at ${SUNSET}"


# Wait for sunset
sunwait ${LOCATION} wait sunset ${SUNSET_OFFSET}

# Activate the end of stream scene 
obs-cli scene current ${SCENEEND}

# Time for ending to play
sleep 30

# End the recording/network stream
obs-cli ${OUTPUT} stop
sleep 5

# Set Control-Q to OBS to exit the program
${HOME}/bin/ydotool key 29:1 16:1 29:0 16:0

# Kill the background scene switch automation
pkill -u ${USER} scene-switcher

# Set the blank delay time to enable the screensaver
gsettings set org.gnome.desktop.session idle-delay 300
